
$background = rgba(100f0fff)

$error = rgba(d14d41ff)

$error_container = rgba(8c1d18ff)

$inverse_on_surface = rgba(100f0fff)

$inverse_primary = rgba(bc5215ff)

$inverse_surface = rgba(fffcf0ff)

$on_background = rgba(cecdc3ff)

$on_error = rgba(601410ff)

$on_error_container = rgba(f9dedcff)

$on_primary = rgba(100f0fff)

$on_primary_container = rgba(cecdc3ff)

$on_primary_fixed = rgba(100f0fff)

$on_primary_fixed_variant = rgba(100f0fff)

$on_secondary = rgba(100f0fff)

$on_secondary_container = rgba(cecdc3ff)

$on_secondary_fixed = rgba(100f0fff)

$on_secondary_fixed_variant = rgba(100f0fff)

$on_surface = rgba(cecdc3ff)

$on_surface_variant = rgba(cecdc3ff)

$on_tertiary = rgba(100f0fff)

$on_tertiary_container = rgba(cecdc3ff)

$on_tertiary_fixed = rgba(100f0fff)

$on_tertiary_fixed_variant = rgba(100f0fff)

$outline = rgba(575653ff)

$outline_variant = rgba(100f0fff)

$primary = rgba(da702cff)

$primary_container = rgba(205ea6ff)

$primary_fixed = rgba(205ea6ff)

$primary_fixed_dim = rgba(da702cff)

$scrim = rgba(000000ff)

$secondary = rgba(da702cff)

$secondary_container = rgba(282726ff)

$secondary_fixed = rgba(da702cff)

$secondary_fixed_dim = rgba(da702cff)

$shadow = rgba(000000ff)

$source_color = rgba(da702cff)

$surface = rgba(100f0fff)

$surface_bright = rgba(343331ff)

$surface_container = rgba(1c1b1aff)

$surface_container_high = rgba(282726ff)

$surface_container_highest = rgba(343331ff)

$surface_container_low = rgba(100f0fff)

$surface_container_lowest = rgba(100f0fff)

$surface_dim = rgba(100f0fff)

$surface_tint = rgba(ec8b49ff)

$surface_variant = rgba(100f0fff)

$tertiary = rgba(da702cff)

$tertiary_container = rgba(282726ff)

$tertiary_fixed = rgba(da702cff)

$tertiary_fixed_dim = rgba(da702cff)
